# Generated by Django 6.0.6 on 2026-07-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Cards/'),
        ),
    ]
