# Generated by Django 6.0.6 on 2026-07-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0002_alter_cards_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
